export const ERRORS_RETURNED = "ERRORS_RETURNED";
export const ERRORS_CLEARED = "ERRORS_CLEARED";

export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_ERROR = "POSTS_ERROR";
export const POST_CREATED = "POST_CREATED";
export const POSTS_FETCHED = "POSTS_FETCHED";
export const POST_RETURNED = "POST_RETURNED";
export const POST_UPDATED = "POST_UPDATED";
export const POST_DELETED = "POST_DELETED";

export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const COMMENT_CREATED = "COMMENT_CREATED";
export const COMMENTS_FETCHED = "COMMENTS_FETCHED";
export const COMMENT_RETURNED = "COMMENT_RETURNED";
export const COMMENT_UPDATED = "COMMENT_UPDATED";
export const COMMENT_DELETED = "COMMENT_DELETED";